In [ ]:
from arcgis.gis import GIS
gis = GIS("home")

# Lab Assignment 2 - GG3209 - Notebook 1
#### Student No. 230012841
#### GitHub Repo: https://github.com/LGroves18/GG3209_Lab_Assignment_2

---------

## Introduction
This notebook contains the solutions for Assignment 2. 

To ensure my work remains structured and manageable, I have decided to split my work into 3 separate notebooks. 

**Notebook 1** (this notebook) covers **Part 1: Python Basics** and **Part 2:  Numpy/Pandas.**

**Notebook 2** covers **Part 3: GeoPandas/RasterRio** 

**Notebook 3** covers **Part 4: Spatial Clustering.**

--------------------

## **Part 1: Python Basics**
#### This section covers topics such as indentation, if functions, strings, and reading files. 
#### I have included both the questions and answers for each task.

### 1.2 Create a script that calculates the average of a list of numbers:

* In a new cell, create a list of numbers, for example: [80, 90, 95, 87, 82]
* Write a function that takes a list of numbers as input, calculates the average, and returns the result.
* Call the function with your list of numbers and print the result.

In [4]:
MATHS = [2,4,6,8,10]
average = sum(MATHS)/len(MATHS)
print("The average of this sum is:", average)

The average of this sum is: 6.0

### 1.3 What's the purpose

Read the following code, and describe in the Markdown cell bellow, What is the purpose of the first two expressions. Explain what they do.

```
import pandas as pd
import geopandas as gpd
dat = pd.read_csv('data/world_cities.csv')  ## Import CSV file
geom = gpd.points_from_xy(dat['lon'], dat['lat'])
geom = gpd.GeoSeries(geom)
dat = gpd.GeoDataFrame(dat, geometry = gpd.GeoSeries(geom), crs = 4326)
dat.to_file('output/world_cities.shp')      ## Export Shapefile
```

#### Answer:
- This is a great question! 
- Import pandas is a package which can open, read and work with regular spreadsheet data like excel or csv files.
- Geopandas is also a package which works with regular spreadsheet data, but it supports mapping and spatial data.

### 1.4 Indentation

Python is sensitive when it comes to indentation. 

Lets try one example, run the following code cell and see what happens and then try to address the issue:

In [5]:
name = 'Dave'
    dogs = 0
print('My name is', name, 'and I own', dogs, 'dogs.')

IndentationError: unexpected indent (4276870405.py, line 2)

Let's fix this!

In [6]:
name = 'Dave'
dogs = 0
print('My name is', name, 'and I own', dogs, 'dogs.')

My name is Dave and I own 0 dogs.

**The problem was the space infront of the word 'dogs' on the second line.**

### 1.5 Strings

Remember you can combine strings. Let's take a look at the following example:

In [7]:
a = "Taco "
b = "time"
c = a + b
print(c)

Taco time

Now in the following code cell,  create a script where you print an string and integer variables. Remember that in Python you can cast the type of variable.

#### My example:

In [8]:
show_title = "Stranger Things"
seasons = 4
message = "I love " + show_title + "! It has " + str(seasons) + " seasons."
print(message)

I love Stranger Things! It has 4 seasons.

### 1.6 Nested *if* conditions

In some cases it might be useful to have nested *if* statements, meaning that you have another layer of conditions after the first condition resolves to True. 

The following example has some issues, address them and check the nested *if* conditional:

In [9]:
season = "Winter"
 temperature = 10

 if season == "Winter":

     if temperature > 7:
         print("No need for winter jacket!")

     else:
         print("It might be cold! Wear a proper jacket!")

elif season == "Summer":

     if temperature > 20:
         print("It's warm! Time to wear shorts!")

     else:
         print("Well this is Finland, better wear long trousers!")
else:
     print("Check the weather forecast!")

IndentationError: unexpected indent (369723711.py, line 2)

Now in the following code cell, create a script with several nested *if* conditions similar than the example above.

My example:

In [10]:
weather = "clear skies"
northernlights = 10

if weather == "rain":
    if northernlights >5:
        print("Aww man, it's raining... but the northern lights are out :( Maybe another night")
    else:
        print("Hey, it's raining, I don't like the northern lights anyway!")

if weather == "clear skies":
    if northernlights >8:
        print("Hey! It's clear skies and northern lights tonight! Let's go out!")
    else:
        print("Hey! Clear skies tonight but unfortunately no northern lights. Oh well.")

Hey! It's clear skies and northern lights tonight! Let's go out!

### 1.7 Functions

Here we have the anatomy of any function in Python

![image.png](attachment:image.png)

source: pythongis.com

In the following example you can see how the function is being created and then we call it to get the returned value.

In [11]:
def celsius_to_fahr(temp):
    return 9 / 5 * temp + 32

Now, create a function to **transform miles to kms** and call it using a 'print' function to show the results

In [12]:
def miles_to_km(miles):
    return miles*1.60934

print(f"5 miles is {miles_to_km(5)}km")

5 miles is 8.0467km

#### **Extra Note:** In some cases it might be useful to know how many times certain value exists in a list. Consider following example:

In [13]:
my_list = ['car', 'bus', 'bike', 'car', 'car', 'bike']
car_count = my_list.count('car')
print("There are", car_count, "cars in my list!")

There are 3 cars in my list!

### 1.8 Create a script that generates a multiplication table:

* Write a function that takes an integer as input and generates a multiplication table for that number, from 1 to 10.
* Call the function with a few different numbers and print the results.
* Optionally, you can use Markdown to format the output as a table.

In [14]:
def multiplication_table(num):
    print("--- Table for", num, "---")
    for i in range(1, 11):
        print(num, "x", i, "=", num * i)
    print()

multiplication_table(5)
multiplication_table(7)

--- Table for 5 ---
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

--- Table for 7 ---
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

### 1.9 Loops

* Define a list named *lunch*, as shown below.

* Use a **for loop** and **conditionals** to create a dictionary with the count of each item in lunch.

* **Hint**: Create an empty dictionary, then use a *for* loop to go over the items, and *a conditional* to add a new item with count 1 (if it is not yet in the dictionary), or to increment an existing item count.
* Write the code and print the result.

In [15]:
lunch = [
    'Salad', 
    'Salad', 
    'Egg', 
    'Beef', 
    'Potato', 
    'Tea',
    'chicken',
    'Potato', 
    'Potato', 
    'Coffee'
]

In [16]:
counts = {}
for item in lunch:
    if item in counts: 
        counts[item] = counts[item]+1
    else:
        counts[item]=1
print(counts)

{'Salad': 2, 'Egg': 1, 'Beef': 1, 'Potato': 3, 'Tea': 1, 'chicken': 1, 'Coffee': 1}

### 1.10 Read files

* Write in the following code cell, a script that reads and prints the **latest_earthquake_world.csv** file, included in the **data** folder.
* Use **pandas** module and print the first 30 rows.
* Hint: Use the second part notebook to get the required help.

In [17]:
import pandas as pd
dataset = '/arcgis/home/Latest_earthquake_world.csv'
df = pd.read_csv(dataset)
df.head(30)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2023-02-23T08:01:02.881Z,38.128000,73.218400,10.000,4.70,mb,75.0,55.00,1.745000,0.6600,...,2023-02-23T08:35:43.040Z,"65 km W of Murghob, Tajikistan",earthquake,4.00,1.907,0.058000,91.0,reviewed,us,us
1,2023-02-23T06:55:34.020Z,18.794600,-63.920500,10.000,3.67,md,19.0,228.00,1.126400,0.5000,...,2023-02-23T08:02:57.172Z,Leeward Islands,earthquake,5.27,4.420,0.130000,14.0,reviewed,pr,pr
2,2023-02-23T06:50:49.137Z,38.487900,72.812200,10.000,4.50,mb,21.0,171.00,1.264000,0.5600,...,2023-02-23T07:28:35.040Z,"106 km WNW of Murghob, Tajikistan",earthquake,8.00,2.000,0.140000,15.0,reviewed,us,us
3,2023-02-23T06:18:13.280Z,-8.548300,-77.625400,66.540,4.70,mb,44.0,154.00,3.503000,0.4700,...,2023-02-23T07:15:40.040Z,"22 km SW of Quiches, Peru",earthquake,8.10,8.700,0.064000,74.0,reviewed,us,us
4,2023-02-23T03:36:09.429Z,-18.287000,-177.826100,524.983,4.90,mb,40.0,63.00,3.626000,0.6700,...,2023-02-23T03:50:54.040Z,NaN,earthquake,13.43,10.963,0.108000,27.0,reviewed,us,us
5,2023-02-23T03:18:57.663Z,-30.391600,-71.685600,34.097,4.40,ml,33.0,187.00,0.285000,0.9400,...,2023-02-23T03:30:52.786Z,"52 km WNW of Ovalle, Chile",earthquake,5.75,5.597,NaN,NaN,reviewed,us,guc
6,2023-02-23T02:18:00.671Z,38.336200,73.106700,10.000,4.70,mb,52.0,60.00,1.529000,0.9400,...,2023-02-23T02:37:56.040Z,Tajikistan-Xinjiang border region,earthquake,6.56,1.897,0.059000,87.0,reviewed,us,us
7,2023-02-23T02:07:46.940Z,38.182200,73.234600,10.000,4.80,mb,21.0,180.00,1.712000,0.8100,...,2023-02-23T02:22:17.040Z,"64 km W of Murghob, Tajikistan",earthquake,6.80,1.992,0.226000,6.0,reviewed,us,us
8,2023-02-23T02:03:42.690Z,18.079300,-68.088800,78.000,3.54,md,14.0,234.00,0.157700,0.2000,...,2023-02-23T02:42:39.960Z,"64 km ESE of Boca de Yuma, Dominican Republic",earthquake,1.66,1.340,0.060000,6.0,reviewed,pr,pr
9,2023-02-23T01:35:57.658Z,38.182400,73.279400,10.000,4.90,mb,27.0,166.00,1.735000,0.7000,...,2023-02-23T01:49:27.040Z,"60 km W of Murghob, Tajikistan",earthquake,7.86,1.985,0.177000,10.0,reviewed,us,us
10,2023-02-23T01:33:25.965Z,59.261500,-153.135600,77.400,2.50,ml,NaN,NaN,NaN,0.5700,...,2023-02-23T01:35:49.711Z,"69 km W of Nanwalek, Alaska",earthquake,NaN,0.700,NaN,NaN,automatic,ak,ak
11,2023-02-23T01:06:05.337Z,38.180400,72.782900,10.000,4.60,mb,20.0,163.00,1.506000,0.6400,...,2023-02-23T01:27:51.040Z,"103 km W of Murghob, Tajikistan",earthquake,7.16,1.772,0.207000,7.0,reviewed,us,us
12,2023-02-23T00:55:14.540Z,38.147400,72.982400,10.000,5.00,mb,84.0,80.00,1.618000,0.8400,...,2023-02-23T01:13:06.040Z,Tajikistan,earthquake,4.66,1.768,0.071000,63.0,reviewed,us,us
13,2023-02-23T00:37:40.397Z,38.072600,73.207700,20.522,6.80,mww,128.0,20.00,1.783000,0.9600,...,2023-02-23T05:49:51.952Z,"67 km W of Murghob, Tajikistan",earthquake,6.93,4.439,0.065000,23.0,reviewed,us,us
14,2023-02-22T23:44:02.170Z,39.145168,-123.260002,1.870,2.91,md,26.0,68.00,0.068420,0.0800,...,2023-02-23T06:29:31.972Z,"4km W of Ukiah, CA",earthquake,0.21,8.330,0.180000,32.0,automatic,nc,nc
15,2023-02-22T23:14:55.147Z,64.931800,-147.252000,148.800,2.90,ml,NaN,NaN,NaN,1.2900,...,2023-02-22T23:18:24.121Z,"12 km WNW of Two Rivers, Alaska",earthquake,NaN,14.300,NaN,NaN,automatic,ak,ak
16,2023-02-22T23:06:22.156Z,53.653800,98.458200,9.707,4.70,mb,64.0,68.00,3.724000,0.6700,...,2023-02-23T00:02:22.040Z,"122 km WSW of Ikey, Russia",earthquake,7.42,4.501,0.053000,106.0,reviewed,us,us
17,2023-02-22T22:05:53.566Z,10.179100,125.063300,10.000,4.60,mb,44.0,120.00,3.131000,0.4600,...,2023-02-23T04:25:16.518Z,"6 km WNW of Liloan, Philippines",earthquake,10.85,1.887,0.077000,51.0,reviewed,us,us
18,2023-02-22T21:39:43.663Z,59.184300,-151.517400,2.000,2.50,ml,NaN,NaN,NaN,1.0800,...,2023-02-22T21:42:36.481Z,"25 km SE of Port Graham, Alaska",earthquake,NaN,3.800,NaN,NaN,automatic,ak,ak
19,2023-02-22T21:18:44.007Z,23.963800,121.774100,8.774,4.40,mb,34.0,83.00,0.266000,0.5100,...,2023-02-22T23:06:06.040Z,"17 km E of Hualien City, Taiwan",earthquake,2.29,4.572,0.126000,18.0,reviewed,us,us
20,2023-02-22T20:01:57.120Z,38.820999,-122.853996,2.640,3.22,ml,52.0,49.00,0.006912,0.0500,...,2023-02-23T03:23:48.835Z,"10km WNW of The Geysers, CA",earthquake,0.15,0.240,0.445000,10.0,automatic,nc,nc
21,2023-02-22T18:22:12.682Z,38.157700,-117.889100,8.700,3.50,ml,13.0,80.53,0.059000,0.1197,...,2023-02-23T02:03:07.570Z,"32 km SE of Mina, Nevada",earthquake,NaN,1.200,0.210000,9.0,reviewed,nn,nn
22,2023-02-22T18:18:25.802Z,-35.700800,-73.161700,35.000,4.30,mb,39.0,150.00,1.045000,0.7200,...,2023-02-22T21:45:30.040Z,NaN,earthquake,4.88,1.955,0.238000,7.0,reviewed,us,us
23,2023-02-22T17:47:55.177Z,-35.748700,-73.151800,35.000,4.00,mb,26.0,198.00,0.998000,0.6600,...,2023-02-22T21:40:26.040Z,"78 km WNW of Cauquenes, Chile",earthquake,4.98,2.007,0.519000,1.0,reviewed,us,us
24,2023-02-22T15:56:47.583Z,61.257000,-150.320300,250.000,2.50,ml,NaN,NaN,NaN,0.9300,...,2023-02-22T21:02:30.323Z,NaN,earthquake,NaN,5.100,NaN,NaN,automatic,ak,ak
25,2023-02-22T15:51:39.859Z,-30.038900,-72.203500,12.059,4.00,mwr,23.0,179.00,0.801000,1.1600,...,2023-02-22T17:15:55.040Z,"83 km W of Coquimbo, Chile",earthquake,2.83,6.844,0.050000,38.0,reviewed,us,us
26,2023-02-22T15:48:21.690Z,40.555832,-124.212669,14.430,3.21,ml,21.0,177.00,0.234100,0.1200,...,2023-02-23T00:44:05.211Z,"5km ESE of Ferndale, CA",earthquake,0.78,0.740,0.302000,10.0,automatic,nc,nc
27,2023-02-22T15:18:06.170Z,18.231000,-68.260500,96.000,3.76,md,15.0,205.00,0.307600,0.2700,...,2023-02-22T15:54:41.369Z,Mona Passage,earthquake,1.72,1.080,0.110000,11.0,reviewed,pr,pr
28,2023-02-22T14:11:28.720Z,19.904167,-155.158333,43.590,3.24,ml,45.0,256.00,NaN,0.1200,...,2023-02-23T08:07:59.549Z,"5 km NW of Honomu, Hawaii",earthquake,0.59,0.950,0.127770,25.0,reviewed,hv,hv
29,2023-02-22T13:12:26.230Z,18.798667,-65.057500,17.130,3.09,md,8.0,259.00,0.454100,0.2100,...,2023-02-22T13:35:31.700Z,Puerto Rico region,earthquake,1.15,1.640,0.037425,4.0,reviewed,pr,pr

---------------------------

## **Part 2: Numpy and Pandas**

### Introduction
In this section, I am practicing how to work with numerical data and tables using two essential Python packages: **Numpy** and **Pandas**. 

While basic Python is great for simple tasks, analyzing geographic and spatial data requires tools that can handle large sets of numbers and tables efficiently.

Numpy (Numerical Python) is used for working with lists of numbers and multi-dimensional grids. 

Pandas (Python Data Analysis) works like a spreadsheet. It lets us import datasets, filter rows, add new calculated columns, and clean up missing data. 

## What to expect in this section
1. Numpy exercises
2. Pandas exercises
3. Final challenge

In [18]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

Array of 10 ones:

In [19]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of the integers 1 to 20:

In [20]:
arr2 = np.arange(1, 21, dtype="int")
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

5 x 5 matrix:

In [21]:
arr3 = np.ones((1,5,5))
print(arr3)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

3D matrix:

In [22]:
arr4 = np.random.rand(3,3,3)
print(arr4)

[[[0.8878217  0.67653661 0.30062547]
  [0.3115696  0.74716049 0.57783477]
  [0.39093114 0.87543455 0.11437766]]

 [[0.16613631 0.56289376 0.46736225]
  [0.7840635  0.59334964 0.17257345]
  [0.49454932 0.14999851 0.04183094]]

 [[0.53555082 0.11433036 0.41077383]
  [0.07530024 0.51104466 0.48565283]
  [0.60064074 0.77065877 0.56122604]]]

Reshaping:

In [23]:
#Here I am trying out different shapes. 
arr5 = arr4.reshape(9,3)
print("Example 1:")
print(" ")
print(arr5)
print(" ")
print("Example 2:")
print(" ")
arr6 = arr4.reshape(3,9)
print(arr6)
print(" ")
print("Example 3:")
print(" ")
arr7 = arr4.reshape(27)
print(arr7)

Example 1:

[[0.8878217  0.67653661 0.30062547]
 [0.3115696  0.74716049 0.57783477]
 [0.39093114 0.87543455 0.11437766]
 [0.16613631 0.56289376 0.46736225]
 [0.7840635  0.59334964 0.17257345]
 [0.49454932 0.14999851 0.04183094]
 [0.53555082 0.11433036 0.41077383]
 [0.07530024 0.51104466 0.48565283]
 [0.60064074 0.77065877 0.56122604]]

Example 2:

[[0.8878217  0.67653661 0.30062547 0.3115696  0.74716049 0.57783477
  0.39093114 0.87543455 0.11437766]
 [0.16613631 0.56289376 0.46736225 0.7840635  0.59334964 0.17257345
  0.49454932 0.14999851 0.04183094]
 [0.53555082 0.11433036 0.41077383 0.07530024 0.51104466 0.48565283
  0.60064074 0.77065877 0.56122604]]

Example 3:

[0.8878217  0.67653661 0.30062547 0.3115696  0.74716049 0.57783477
 0.39093114 0.87543455 0.11437766 0.16613631 0.56289376 0.46736225
 0.7840635  0.59334964 0.17257345 0.49454932 0.14999851 0.04183094
 0.53555082 0.11433036 0.41077383 0.07530024 0.51104466 0.48565283
 0.60064074 0.77065877 0.56122604]

# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [24]:
arr8 = np.linspace(1,10,20)
print(arr8)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]

## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [25]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

In [26]:
20

20

In [27]:
print(a)
print(" ")
print(a[3,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [28]:
print(a[1:,3:])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]

```python
array([ 6,  7,  8,  9, 10])
```

In [29]:
a[1]

array([ 6,  7,  8,  9, 10])

## 2.5 

Calculate the sum of all the numbers in `a`.

In [31]:
np.sum(a)

np.int64(325)

## 2.6 

Calculate the sum of each row in `a`.

In [32]:
print(np.sum(a, axis=1))

[ 15  40  65  90 115]

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [33]:
print("The mean is as follows:")
print(np.mean(a))
BigBoolMask = a > np.mean(a)
print("So, the answer is:")
print(a[BigBoolMask])

The mean is as follows:
13.0
So, the answer is:
[14 15 16 17 18 19 20 21 22 23 24 25]

## Pandas

## 2.8

In this we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [35]:
import numpy as np
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
df.head(10)

     country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [37]:
print(len(df))
print(len(df.columns))
#1430 rows and 4 columns... right? YES :D

1430
4

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [38]:
CO2mean = df["co2_emmission"].mean()
print(CO2mean)

74.383993006993

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [39]:
# Here's the maximum CO2 emmissions:
CO2MAX = df["co2_emmission"].max()
print(CO2MAX)

1712.0

In [40]:
# Find the row index of the maximum CO2 emmission:
MAX_INDEX = df["co2_emmission"].idxmax()
print(MAX_INDEX)

2

In [41]:
# Now for the food type and country:
FOODTYPE = df.loc[MAX_INDEX, "food_category"]
COUNTRY = df.loc[MAX_INDEX, "country"]
MAX_CO2 = df["co2_emmission"]
print(df.loc[[2],["co2_emmission", "food_category", "country"]])

   co2_emmission food_category    country
2         1712.0          Beef  Argentina

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [44]:
# Thought process: some sort of boolean equation? Nope. It's a query...?
HIGHCO2 = df[(df["co2_emmission"]>1000) & (df["food_category"]=="Beef")]
print(HIGHCO2.head(20))
print("")
print(len(HIGHCO2))

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94

5

## 2.14

Which country consumes the least amount of beef per person per year?

In [45]:
# code comes here

leastbeef = df["consumption"].min()
print(leastbeef)

beefindex = df["consumption"].idxmin()
print(beefindex)

nobeef = df[(df["consumption"]<1) & (df["food_category"] == "Beef")]
print(nobeef)

0.0
9
      country food_category  consumption  co2_emmission
1333    India          Beef         0.81          24.99
1410  Liberia          Beef         0.78          24.07

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [50]:
# 1st step - define the categories
meat_products = ['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']
print(meat_products)

['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']

In [47]:
#2nd step - filter the dataframe. 
meat_df = df[df['food_category'].isin(meat_products)]
print(meat_df.head(5))

     country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96

In [48]:
#3rd step - sum the emissions
total_meat_co2 = meat_df['co2_emmission'].sum()
print("Total CO2 emissions for all meat products combined:")
print(total_meat_co2)

Total CO2 emissions for all meat products combined:
74441.13

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [53]:
meat_products = ['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']
print(meat_products)

non_meat_df = df[~df['food_category'].isin(meat_products)]
print(non_meat_df.head(5))

#3rd step - sum the emissions
total_non_meat_co2 = non_meat_df['co2_emmission'].sum()
print("Total CO2 emissions for all meat products combined:")
print(total_non_meat_co2)

the_total = df["co2_emmission"].sum()
print(the_total)

#JUST CHECKING AND IT's CORRECT!!!! YAY
print(the_total - total_non_meat_co2)

['Pork', 'Poultry', 'Fish', 'Lamb & Goat', 'Beef']
     country             food_category  consumption  co2_emmission
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00
Total CO2 emissions for all meat products combined:
31927.98
106369.10999999999
74441.12999999999

## Final Challenge

In [55]:
# Step 1: upload the files to ArcGIS Online
# Step 2: Read the file as a Pandas dataframe

In [57]:
# I am checking the name of the dataset and file path: 
dataset = '/arcgis/home/world_cities.csv'

In [60]:
# Here I will creating the dataframe:
df = pd.read_csv('/arcgis/home/world_cities.csv')

In [61]:
# Now I want to see the first 10 rows:
df.head(10)

                 city       country    pop    lat    lon  capital
0  'Abasan al-Jadidah     Palestine   5629  31.31  34.34        0
1  'Abasan al-Kabirah     Palestine  18999  31.32  34.35        0
2        'Abdul Hakim      Pakistan  47788  30.55  72.11        0
3  'Abdullah-as-Salam        Kuwait  21817  29.36  47.98        0
4               'Abud     Palestine   2456  32.03  35.07        0
5             'Abwein     Palestine   3434  32.03  35.20        0
6            'Adadlay       Somalia   9198   9.77  44.65        0
7              'Adale       Somalia   5492   2.75  46.30        0
8               'Afak          Iraq  22706  32.07  45.26        0
9               'Afif  Saudi Arabia  41731  23.92  42.93        0

In [62]:
# Here I will create the new "Pop_M" column by dividing "pop" by 1,000,000
df['pop_M'] = df['pop'] / 1_000_000

In [64]:
# I want to check that the new column I just created is there and correct.
df.head(5)

                 city    country    pop    lat    lon  capital     pop_M
0  'Abasan al-Jadidah  Palestine   5629  31.31  34.34        0  0.005629
1  'Abasan al-Kabirah  Palestine  18999  31.32  34.35        0  0.018999
2        'Abdul Hakim   Pakistan  47788  30.55  72.11        0  0.047788
3  'Abdullah-as-Salam     Kuwait  21817  29.36  47.98        0  0.021817
4               'Abud  Palestine   2456  32.03  35.07        0  0.002456

In [65]:
# Now I will remove the original pop column
df = df.drop(columns=['pop'])

In [69]:
# Now i'm checking that pop is no longer there
df.head(3)

                 city    country    lat    lon  capital     pop_M
0  'Abasan al-Jadidah  Palestine  31.31  34.34        0  0.005629
1  'Abasan al-Kabirah  Palestine  31.32  34.35        0  0.018999
2        'Abdul Hakim   Pakistan  30.55  72.11        0  0.047788

In [81]:
# The city I've picked is Los Angeles, USA. 
my_city = df[df['city'] == 'Los Angeles']
my_city.head()

              city country    lat     lon  capital    pop_M
21434  Los Angeles   Chile -37.46  -72.36        0  0.12604
21435  Los Angeles     USA  34.11 -118.41        0  3.91150

In [84]:
# I just want the USA Los Angeles:
my_city = df[(df['city'] == 'Los Angeles') & (df['country'] == 'USA')]
my_city.head()

              city country    lat     lon  capital   pop_M
21435  Los Angeles     USA  34.11 -118.41        0  3.9115

In [88]:
# Now I will filter for all cities in the United States and get the 5 largest using pop_M
us_cities = df[df['country'] == 'USA']
top_5_us_cities = us_cities.nlargest(5, 'pop_M')
top_5_us_cities.head()

              city country    lat     lon  capital     pop_M
25877     New York     USA  40.67  -73.94        0  8.124427
21435  Los Angeles     USA  34.11 -118.41        0  3.911500
7366       Chicago     USA  41.84  -87.68        0  2.830144
14769      Houston     USA  29.77  -95.39        0  2.043005
28856      Phoenix     USA  33.54 -112.07        0  1.450884

--------------------

## Summary & Next Steps
### Notebook 1 Completed
In this notebook, I have completed:
Part 1: Python Basics exercises
Part 2: NumPy and Pandas exercises, concluding with the World Cities Final Challenge. 

### Continuation: Notebook 2
The remaining parts of Lab Assignment 2 are completed in Notebooks 2 and 3